[package]
name = "tnfilt"
version = "0.1.0"
authors = ["Russell Mull <russell@auxon.io>"]
edition = "2018"

[dependencies]
nom = "4.2.3"

[dev-dependencies]
typenum = "1.11.2"
assert_cmd = "0.11"
proptest = "0.9.4"
bitvec = "0.15.2"